version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '2'
    restart: always
    container_name: chat-pre-frontend
  server:
    build:
      context: ./service
      dockerfile: Dockerfile
    volumes:
      - ./data/logs:/app/logs
    depends_on:
      - mongodb
      - redis
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '2'
    restart: always
    container_name: chat-pre-server
  redis:
    image: redis
    command: redis-server --requirepass lfluYk4reffZDjzzXfeNA2ub9odfJ1Ic
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '2'
    restart: always
    container_name: chat-pre-redis
  mongodb:
    image: mongo:4.4.6
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbroot
      MONGO_INITDB_ROOT_PASSWORD: Gri42Mvyk3j2PXIiTdn6CCA8JDSST7yv
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '2'
    restart: always
    container_name: chat-pre-mongodb
    